"""init

Revision ID: 4254adfb5e5b
Revises: 
Create Date: 2025-08-07 19:47:44.684953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4254adfb5e5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrapping',
    sa.Column('Scrapping_id', sa.Integer(), nullable=False),
    sa.Column('Steam_id', sa.String(length=255), nullable=True),
    sa.Column('Page', sa.Integer(), nullable=True),
    sa.Column('Game', sa.String(length=255), nullable=True),
    sa.Column('Genre', sa.String(length=255), nullable=True),
    sa.Column('Rating', sa.String(length=255), nullable=True),
    sa.Column('Review', sa.Text(), nullable=True),
    sa.Column('Playtime', sa.String(length=255), nullable=True),
    sa.Column('PostedDate', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Scrapping_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('scrapping')
    # ### end Alembic commands ###
