"""update

Revision ID: a68322daca5c
Revises: c056dc446405
Create Date: 2025-08-13 07:07:34.276405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a68322daca5c'
down_revision = 'c056dc446405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segmentasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segmentation_csv_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('membership_csv_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('karakteristik_json_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('interpretasi_json_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_segmentasi_dominant_archetype'))
        batch_op.drop_index(batch_op.f('ix_segmentasi_steam_id'))
        batch_op.drop_column('archetype_9_weight')
        batch_op.drop_column('top_3_genres')
        batch_op.drop_column('archetype_2_weight')
        batch_op.drop_column('total_achievements')
        batch_op.drop_column('archetype_3_weight')
        batch_op.drop_column('archetype_5_weight')
        batch_op.drop_column('archetype_4_weight')
        batch_op.drop_column('steam_id')
        batch_op.drop_column('archetype_7_weight')
        batch_op.drop_column('archetype_10_weight')
        batch_op.drop_column('archetype_6_weight')
        batch_op.drop_column('archetype_8_weight')
        batch_op.drop_column('dominant_archetype')
        batch_op.drop_column('avg_playtime')
        batch_op.drop_column('total_games')
        batch_op.drop_column('dominant_topic_user')
        batch_op.drop_column('archetype_1_weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segmentasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archetype_1_weight', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('dominant_topic_user', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_games', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('avg_playtime', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('dominant_archetype', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('archetype_8_weight', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('archetype_6_weight', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('archetype_10_weight', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('archetype_7_weight', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('steam_id', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('archetype_4_weight', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('archetype_5_weight', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('archetype_3_weight', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('total_achievements', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('archetype_2_weight', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('top_3_genres', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('archetype_9_weight', mysql.FLOAT(), nullable=True))
        batch_op.create_index(batch_op.f('ix_segmentasi_steam_id'), ['steam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_segmentasi_dominant_archetype'), ['dominant_archetype'], unique=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('interpretasi_json_path')
        batch_op.drop_column('karakteristik_json_path')
        batch_op.drop_column('membership_csv_path')
        batch_op.drop_column('segmentation_csv_path')

    # ### end Alembic commands ###
