"""update

Revision ID: c056dc446405
Revises: d6421dbf504f
Create Date: 2025-08-10 09:41:04.526532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c056dc446405'
down_revision = 'd6421dbf504f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segmentasi',
    sa.Column('Segmentasi_id', sa.Integer(), nullable=False),
    sa.Column('Proses_id', sa.Integer(), nullable=True),
    sa.Column('steam_id', sa.String(length=20), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('avg_playtime', sa.Float(), nullable=True),
    sa.Column('total_achievements', sa.Integer(), nullable=True),
    sa.Column('top_3_genres', sa.String(length=255), nullable=True),
    sa.Column('dominant_topic_user', sa.Integer(), nullable=True),
    sa.Column('dominant_archetype', sa.Integer(), nullable=True),
    sa.Column('archetype_1_weight', sa.Float(), nullable=True),
    sa.Column('archetype_2_weight', sa.Float(), nullable=True),
    sa.Column('archetype_3_weight', sa.Float(), nullable=True),
    sa.Column('archetype_4_weight', sa.Float(), nullable=True),
    sa.Column('archetype_5_weight', sa.Float(), nullable=True),
    sa.Column('archetype_6_weight', sa.Float(), nullable=True),
    sa.Column('archetype_7_weight', sa.Float(), nullable=True),
    sa.Column('archetype_8_weight', sa.Float(), nullable=True),
    sa.Column('archetype_9_weight', sa.Float(), nullable=True),
    sa.Column('archetype_10_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['Proses_id'], ['steam_id_proses.Proses_id'], ),
    sa.PrimaryKeyConstraint('Segmentasi_id')
    )
    with op.batch_alter_table('segmentasi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segmentasi_dominant_archetype'), ['dominant_archetype'], unique=False)
        batch_op.create_index(batch_op.f('ix_segmentasi_steam_id'), ['steam_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segmentasi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segmentasi_steam_id'))
        batch_op.drop_index(batch_op.f('ix_segmentasi_dominant_archetype'))

    op.drop_table('segmentasi')
    # ### end Alembic commands ###
