"""update

Revision ID: d6421dbf504f
Revises: 
Create Date: 2025-08-09 15:03:37.276399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6421dbf504f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrapping',
    sa.Column('Scrapping_id', sa.Integer(), nullable=False),
    sa.Column('Steam_ID', sa.String(length=255), nullable=True),
    sa.Column('Page', sa.Integer(), nullable=True),
    sa.Column('Game', sa.String(length=255), nullable=True),
    sa.Column('Genre', sa.String(length=255), nullable=True),
    sa.Column('Rating', sa.String(length=255), nullable=True),
    sa.Column('Review', sa.Text(), nullable=True),
    sa.Column('Playtime', sa.String(length=255), nullable=True),
    sa.Column('PostedDate', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Scrapping_id')
    )
    op.create_table('topic_modeling',
    sa.Column('Topic_id', sa.Integer(), nullable=False),
    sa.Column('Keyword', sa.Text(), nullable=True),
    sa.Column('Cluster', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Topic_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('steam_id_proses',
    sa.Column('Proses_id', sa.Integer(), nullable=False),
    sa.Column('Steam_id', sa.String(length=255), nullable=True),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('Proses_id')
    )
    op.create_table('proses_topic_association',
    sa.Column('Proses_id', sa.Integer(), nullable=False),
    sa.Column('Topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Proses_id'], ['steam_id_proses.Proses_id'], ),
    sa.ForeignKeyConstraint(['Topic_id'], ['topic_modeling.Topic_id'], ),
    sa.PrimaryKeyConstraint('Proses_id', 'Topic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proses_topic_association')
    op.drop_table('steam_id_proses')
    op.drop_table('users')
    op.drop_table('topic_modeling')
    op.drop_table('scrapping')
    # ### end Alembic commands ###
