"""update

Revision ID: de231518a1c7
Revises: fad99da3e53c
Create Date: 2025-08-16 09:53:24.599340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de231518a1c7'
down_revision = 'fad99da3e53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_id_proses', schema=None) as batch_op:
        batch_op.alter_column('Steam_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_id_proses', schema=None) as batch_op:
        batch_op.alter_column('Steam_id',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
