"""update

Revision ID: fad99da3e53c
Revises: a68322daca5c
Create Date: 2025-08-13 07:24:09.534693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad99da3e53c'
down_revision = 'a68322daca5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_game_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.String(length=20), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(length=255), nullable=True),
    sa.Column('playtime_hours', sa.Float(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('achievements', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_game_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_game_data_steam_id'), ['steam_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_game_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_game_data_steam_id'))

    op.drop_table('player_game_data')
    # ### end Alembic commands ###
